name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    name: run cargo tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-index

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-build-target

      - name: Install Surfpool
        run: |
          brew tap txtx/taps
          brew install txtx/taps/surfpool

      - name: Install Solana + Anchor
        shell: bash
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          cargo install anchor-cli@0.32.1

      - name: Create deploy directory
        run: mkdir -p target/deploy

      - name: Write Portal keypair
        run: echo "${{ secrets.PORTAL_KEYPAIR }}" > target/deploy/portal-keypair.json

      - name: Write Wormhole Adapter keypair
        run: echo "${{ secrets.WORMHOLE_ADAPTER_KEYPAIR }}" > target/deploy/wormhole_adapter-keypair.json

      - name: Write Hyperlane Adapter keypair
        run: echo "${{ secrets.HYPERLANE_ADAPTER_KEYPAIR }}" > target/deploy/hyperlane_adapter-keypair.json

      - name: Build programs
        run: anchor build
        shell: bash

      - name: Run tests
        run: make test-verbose
